/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entidades;

import Atxy2k.CustomTextField.RestrictedTextField;
import Clases.Pokemon;
import javax.swing.JOptionPane;


/**
 *
 * @author alumno
 */
public class CambiarNombrePokimon extends javax.swing.JFrame {
    String NombrePokemon = null;
    public static String sobrenombre = "";
    /**
     * Creates new form CambiarNombrePokimon
     */
    public CambiarNombrePokimon() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        if (JFElegirPokemon.jRadioButton1.isSelected()){
            NombrePokemon = JFElegirPokemon.jLabel5.getText();
            jLabel2.setText(NombrePokemon);
        }
        else if (JFElegirPokemon.jRadioButton2.isSelected()){
            NombrePokemon = JFElegirPokemon.jLabel6.getText();
            jLabel2.setText(NombrePokemon);
        }
        else if (JFElegirPokemon.jRadioButton3.isSelected()){
            NombrePokemon = JFElegirPokemon.jLabel7.getText();
            jLabel2.setText(NombrePokemon);
        }
        restngirCaracteres();
    }
    public void restngirCaracteres(){
        RestrictedTextField a = new RestrictedTextField(jTextField1);
        a.setLimit(10);
        a.setOnlyAlphaNumeric(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOMBRE DEL POKIMON");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("MODIFICAR NOMBRE DEL POKIMON");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1.setText("MANTENER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, 40));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton3.setText("ATRAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 190, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenePokemones/pokebola.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFElegirPokemon marco2 = new JFElegirPokemon();
        marco2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JFElegirPokemon.jRadioButton1.isSelected()){
            JFBatalla1 batalla = new JFBatalla1();
            JFBatalla1.jLabel7.setText(NombrePokemon);
            batalla.setVisible(true);
        }
        else if (JFElegirPokemon.jRadioButton2.isSelected()){
            JFBatalla2 batalla = new JFBatalla2();
            JFBatalla2.jLabel7.setText(NombrePokemon);
            batalla.setVisible(true);
            
        }
        else if (JFElegirPokemon.jRadioButton3.isSelected()){
            JFBatalla3 batalla = new JFBatalla3();
            JFBatalla3.jLabel7.setText(NombrePokemon);
            batalla.setVisible(true);
        }
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().length()==0){
            JOptionPane.showMessageDialog(null, "ERROR... Ingrese un sobrenombre al pokemon \n "
                    + "en caso contrario mantener el nombre por defecto");
        }
        else{
            sobrenombre = jTextField1.getText();
            if (JFElegirPokemon.jRadioButton1.isSelected()){
                JFBatalla1 batalla = new JFBatalla1();
                JFBatalla1.jLabel7.setText(jTextField1.getText());
                batalla.setVisible(true);
            }
            else if (JFElegirPokemon.jRadioButton2.isSelected()){
                JFBatalla2 batalla = new JFBatalla2();
                JFBatalla2.jLabel7.setText(jTextField1.getText());
                batalla.setVisible(true);
            }
            else if (JFElegirPokemon.jRadioButton3.isSelected()){
                JFBatalla3 batalla = new JFBatalla3();
                JFBatalla3.jLabel7.setText(jTextField1.getText());
                batalla.setVisible(true);
            }
            dispose();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarNombrePokimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarNombrePokimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarNombrePokimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarNombrePokimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarNombrePokimon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
